### ISSUE TITLE
Update team page with officer images

### ISSUE THREAD

**Issue by Fernando4242** [AIAAUTDallas/front-end#22]
### Description
Would be good to update the team page with images of everyone and see if there has been any position changes.

### Resources
- https://nextjs.org/docs/pages/building-your-application/optimizing/images

**Comment by stteeevv** [comment]
photoshoot of all officers happening soon, we can get this done after we get the pics

**Comment by Fernando4242** [comment]
This can be done at the same time as #31 or after.

**Comment by stteeevv** [comment]
pics still being edited
