### ISSUE TITLE
inconsistency between pages

### ISSUE THREAD

**Issue by stteeevv** [AIAAUTDallas/front-end#54]

**Comment by stteeevv** [comment]
we should try and have some uniform layout between pages
at the minimum let's have a section for each page that reiterates what page you're on to have some consistency
example of inconsistency
![image](https://github.com/AIAAUTDallas/front-end/assets/45155637/2276c732-d182-4901-86ab-206f442a3e67)
![image](https://github.com/AIAAUTDallas/front-end/assets/45155637/02e22c6f-c40b-4542-9060-e3c6040d49f3)

**Comment by stteeevv** [comment]
ok we're gonna have a picture at the top of each page with some text, similar to home page

**Comment by Fernando4242** [comment]
We can make it look like the newsletter and add a background picture for that size. A big image might be too much like the home page.
